# Import .env file as properties
spring.config.import=optional:file:.env[.properties]

# JWT Security Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}
